### ISSUE TITLE
[Device Support] Plex HTPC App Control On Windows.

### ISSUE THREAD

**Issue by 7gxycn08** [nicko88/HTWebRemote#5]
Created a Plex HTPC Windows app template.
Added Buttons:
1. Up.
2. Down.
3. Left.
4. Right.
5. Ok (which also controls playback and pause).
6. Back (which also exits videos and reaches the exit menu).
7. Volume controls + and - and ? current percentage.
8. Aspect Ratio (which switches playing video aspect ratio).
9. Added a Start Plex HTPC button that runs a custom bat script which starts Plex HTPC app using absolute path and brings it to the foreground so the key presses register.

The json template and .bat script are included in the zip.
[PlexHTPC-Windows.zip](https://github.com/user-attachments/files/17999071/PlexHTPC-Windows.zip)

**Comment by nicko88** [comment]
Nice.  Not sure if a Issue is the best place to put this though.

Can you add a section to the Wiki about it maybe?  Or maybe under Discussions?

Or you can post it on the AVSForum thread, but I can understand if you don't want to make an account there for that if you don't have one.

**Comment by 7gxycn08** [comment]
> Nice. Not sure if a Issue is the best place to put this though.
> 
> Can you add a section to the Wiki about it maybe? Or maybe under Discussions?
> 
> Or you can post it on the AVSForum thread, but I can understand if you don't want to make an account there for that if you don't have one.

My bad wasn't sure how to contribute. I'll just post it on AVSForum thread and you can add it to your Github page the way you like If you want.

Please close the issue.
